#!/bin/bash

# FIXME: this should all just be rolled into the debian/rules file
# so the package can be auto-built by the usual mechanism.  This
# shouldn't be too hard, though, and it's simpler to fix bugs with
# this as a separate script.

set -e

CONTROL_TEMPLATE=debian/control.template
CONTROL=debian/control

export DISTRO=`lsb_release -is`

if [ $DISTRO == "Debian" ]
then
    sed s/@@SUN_JAVA_PACKAGE_VERSION@@/6-07-4/ < $CONTROL_TEMPLATE > $CONTROL
elif [ $DISTRO == "Ubuntu" ]
then
    sed s/@@SUN_JAVA_PACKAGE_VERSION@@/6-03-0ubuntu2/ < $CONTROL_TEMPLATE > $CONTROL
else
    echo Unknown distribution $DISTRO
    exit -1
fi

DEB_HOST_ARCH=`dpkg-architecture -qDEB_HOST_ARCH`
DEB_BUILD_ARCH=`dpkg-architecture -qDEB_BUILD_ARCH`

CWD=`pwd`

# We don't want everything from the java subdirectory, but preserve
# the Linux Java 3D files:
if [ $DEB_BUILD_ARCH == "i386" ]
then
    J=java/linux/jdk1.6.0_06/jre/lib/
    tar czvf preserved-java.tar.gz \
	${J}ext/j3dcore.jar \
	${J}ext/j3dutils.jar \
	${J}ext/vecmath.jar \
	${J}i386/libj3dcore-ogl-cg.so \
	${J}i386/libj3dcore-ogl.so
    JAVA3D_CLASSES="$CWD/${J}ext/j3dcore.jar:"
    JAVA3D_CLASSES="${JAVA3D_CLASSES}$CWD/${J}ext/j3dutils.jar:"
    JAVA3D_CLASSES="${JAVA3D_CLASSES}$CWD/${J}ext/vecmath.jar:"
    JAVA3D_CLASSES="${JAVA3D_CLASSES}$CWD/${J}i386/libj3dcore-ogl-cg.so:"
    JAVA3D_CLASSES="${JAVA3D_CLASSES}$CWD/${J}i386/libj3dcore-ogl.so"
    export JAVA_HOME=/usr/lib/jvm/java-6-sun-1.6.0.07/
elif [ $DEB_BUILD_ARCH == "amd64" ]
then
    J=java/linux-amd64/jdk1.6.0_04/jre/lib/
    tar czvf preserved-java.tar.gz \
	${J}ext/j3dcore.jar \
	${J}ext/j3dutils.jar \
	${J}ext/vecmath.jar \
	${J}amd64/libj3dcore-ogl.so
    JAVA3D_CLASSES="$CWD/${J}ext/j3dcore.jar:"
    JAVA3D_CLASSES="${JAVA3D_CLASSES}:$CWD/${J}ext/j3dutils.jar:"
    JAVA3D_CLASSES="${JAVA3D_CLASSES}:$CWD/${J}ext/vecmath.jar:"
    JAVA3D_CLASSES="${JAVA3D_CLASSES}:$CWD/${J}amd64/libj3dcore-ogl.so"
    export JAVA_HOME=/usr/lib/jvm/java-6-sun-1.6.0.06/
fi

export JAVA3D_CLASSES

# FIXME: we should have a less brutal way of doing this.  The problem
# is that the -I option to dpkg-buildpackage (passed on to
# dpkg-source) isn't flexible enough to specify that we only want to
# keep particular files from the java directory.  A better solution
# may be to maintain separate branches of the java/linux*
# subdirectories, but it would but nice to still be building from the
# master branch.

rm -rf java/*
tar xzvf preserved-java.tar.gz
rm preserved-java.tar.gz

dpkg-buildpackage -rfakeroot -us -uc
