#!/bin/sh

set -e

CONTROL_TEMPLATE=debian/control.template
CONTROL=debian/control

CHANGELOG_TEMPLATE=debian/changelog.template
CHANGELOG=debian/changelog

if test xdebian == x$1
then
    UBUNTU_SUFFIX=
    SUN_JAVA_PACKAGE_VERSION=6-07-4
elif test xubuntu == x$1
then
    UBUNTU_SUFFIX=ubuntu
    SUN_JAVA_PACKAGE_VERSION=6-03-0ubuntu2
else
    echo "Usage: ./switch-target-distribution [DISTRIBUTION]"
    echo "... where [DISTRIBUTION] can be debian or ubuntu."
    exit 1
fi

DISTRO=`lsb_release -is`
if test x$DISTRO == xDebian
then
    JDK_BUILD_VERSION=6-07-4
elif test x$DISTRO == xUbuntu
then
    JDK_BUILD_VERSION=6-03-0ubuntu2
else
    echo "This is an unknown distribution $DISTRO"
    exit 1
fi

sed -e s/@@SUN_JAVA_PACKAGE_VERSION@@/${SUN_JAVA_PACKAGE_VERSION}/ -e s/@@JDK_BUILD_VERSION@@/${JDK_BUILD_VERSION}/ < ${CONTROL_TEMPLATE} > ${CONTROL}

sed s/@@UBUNTU_SUFFIX@@/${UBUNTU_SUFFIX}/ < ${CHANGELOG_TEMPLATE} > ${CHANGELOG}

VERSION_IN_CHANGELOG=`perl -e 'use Dpkg::Changelog qw(parse_changelog); print parse_changelog->{version}'`
PACKAGE_IN_CHANGELOG=`perl -e 'use Dpkg::Changelog qw(parse_changelog); print parse_changelog->{source}'`

CWD_BASENAME=$(basename `realpath .`)
REQUIRED_DIRECTORY_NAME=${PACKAGE_IN_CHANGELOG}-${VERSION_IN_CHANGELOG}

if test $CWD_BASENAME != $REQUIRED_DIRECTORY_NAME
then
    echo "Warning: the current directory name (${CWD_BASENAME}) does not match"
    echo "the package name and version in the new changelog."
    echo "Rename this directory to: ${REQUIRED_DIRECTORY_NAME}"
fi
