'\" te
.TH javaws 1 "22 Jun 2004" "" ""
.SH "NAME"
javaws \- Java Web Start command launcher
.SH "SYNOPSIS"
.PP
\fBjavaws\fR [ [ options ] ] \ 
\fI[ URL ]\fR
.SH "PARAMETERS"
.PP
Options may be in any order\&. For a discussion of a specific option,
see OPTIONS below\&.
.IP "options" 6
Command-line
options\&. See OPTIONS below\&.
.IP "URL" 6
Uniform Resource
Locator (\fIURL\fR) of the JNLP (Java Network Launching
Protocol) file\&.
.SH ""
.PP
The \fBjavaws\fR
command launches Java Web Start, which is the reference implementation of
the Java Network Launching Protocol (JNLP)\&.  Java Web Start launches Java
application/applets hosted on a network\&. 
.PP
Without any options \fBjavaws\fR will launch the Java Application
Cache Viewer\&.
.PP
If a URL specifying a JNLP (Java Network Launching Protocol) file is
specified, \fBjavaws\fR will launch the Java application/applet
specified in the JNLP file\&.
.SH "OPTIONS"
.PP
The \fBjavaws\fR launcher has a set of options that are
supported in the current release\&.  However, the options may be removed in
a future release\&.  All -\fBX\fR options are non-standard and subject
to change\&.
.IP "-\fBonline\fR" 6
Runs in
online mode (default behavior)\&.
.IP "-\fBoffline\fR " 6
Runs Java
Web Start in offline mode\&.
.IP "-\fBXclearcache\fR" 6
Clears
the user\&'s cache\&.  Java Web Start will exit after the command has completed\&.
.IP "-\fBuninstall\fR\fI URL\fR" 6
Removes a specific application/applet from the user\&'s cache,
as indicated by the \fIURL\fR for the JNLP file\&. Java
Web Start will exit after the command has completed\&.
.IP "-\fBimport\fR" 6
Imports
the application specified by the \fIURL\fR into the user\&'s
cache (without running it)
.IP "-\fBsilent\fR" 6
Iimports
in silent mode, when used with \(emimport (ie\&. no UI will be displayed)\&.
.IP "-\fBcodebase\fR\fI URL\fR" 6
Replaces the codebase with \fIURL\fR
 (\fI\fIURL \fR\fR must be valid)
in the JNLP file specified when importing the resources\&.
.IP "-\fBsystem\fR" 6
Uses the
system cache instead of the user cache\&.
.IP "-\fBshortcut\fR" 6
Allows
the creation of shortcuts during silent import\&.
.IP "-\fBassociation\fR" 6
Allows
the creation of associations during silent import\&. 
.IP "-\fBopen arguments\fR" 6
Replaces the arguments in the JNLP file with "-open arguments"\&.
.IP "-\fBprint arguments\fR" 6
Replaces the arguments in the JNLP file with "-print arguments"\&.
.IP "-\fBuserConfig \fR\fIproperty-name\fR" 6
Clears the specified deployment property
 \fIproperty-name\fR\&. Java Web Start will then exit\&.
.IP "-\fBuserConfig  \fR\fIproperty-name\fR \fIproperty-value\fR" 6
Sets the specified deployment \fIproperty-name\fR
to the specified \fIproperty-value\fR\&. Java Web Start
will then exit\&.
.IP "-\fBupdateVersions\fR" 6
Updates the Java Web Start configuration file based on the current machine\&'s
settings\&. Java Web Start will then exit\&.
.IP "-\fBXnosplash\fR" 6
Disable
the display of the initial splash screen\&.
.IP "-\fBviewer\fR" 6
Runs the
Java Application Cache Viewer (default if no URL is specified)\&.
.IP "-\fBwait\fR" 6
The javaws
process will not exit until the application exits\&.
.SH "EXIT STATUS"
.PP
The following exit values are returned:
.IP "0 " 6
Successful completion\&.
.IP ">0" 6
An error occurred\&.
.SH "FILES"
.IP "\fB~/Library/Caches/Java/deployment\&.properties\fR" 6
User configuration file for Java Deployment
Products
.IP "\fB/System/Library/Frameworks/JavaVM.framework/Versions/1.5.0/Home/deployment\&.config\fR" 6
Enterprise configuration file for Java Deployment Products\&.
.IP "\fB/System/Library/Frameworks/JavaVM.framework/Versions/1.5.0/Home/lib/deployment\&.config\fR" 6
Alternate Enterprise configuration file for Java Deployment
Products\&.
.IP "\fB$HOME/\&.mailcap\fR" 6
User\&'s mailcap file to specify helper applications for Netscape/Mozilla Browser
.IP "\fB$HOME/\&.mime\&.types\fR" 6
User\&'s mime-type file to specify mime-types supported in Netscape/Mozilla
Browser 
.IP "\fB/etc/mailcap\fR" 6
System mailcap file to specify helper applications for Netscape/Mozilla Browser
.IP "\fB/etc/mime\&.types\fR" 6
System mime-type file to specify mime-types supported in Netscape/Mozilla
Browser
.SH ""
.PP
\fBjava\fR(1), \fBjar\fR(1), \fBpack200\fR(1), \fBattributes\fR(5) 
.PP
http://java\&.sun\&.com/j2se/1\&.5\&.0/docs
...\" created by instant / solbook-to-man, Mon 23 Feb 2004, 10:03
