.TH IMAGEJA 1
.\"
.\" imageja.1: 
.\"
.\" Version 0.9.0
.\"

.\" Text begins
.SH NAME
imageja \- Image Processing and Analysis in Java
.SH SYNOPSIS
.B imageja
[\fIOPTION\fR]... [FILENAME]...
.SH DESCRIPTION
.PP
[There should be a description here...]
.SH OPTIONS
.TP
\fB\-ijpath \fIDIRECTORY\fR
Specifies the path to the directory containing the plugins
directory.  So, if you put plugins in ~/.imageja/plugins/ then
you would pass -ijpath ~/.imageja/
.TP
\fB-port\fIN\fR
.nf
Specifies the port ImageJ uses to determine if another instance is running
Example 1: -port1 (use default port address + 1)
Example 2: -port2 (use default port address + 2)
Example 3: -port0 (do not check for another instance)
(The default port is 57294.)
.fi
.TP
\fB-macro \fIPATH [\fIARG\fR]
.nf
Runs a macro, passing it an optional argument
Example 1: -macro analyze.ijm
Example 2: -macro analyze /Users/wayne/images/stack1
.fi
.TP
\fB-eval \fIMACRO-EXPRESSION\fR
.nf
Evaluates macro code
Example 1: -eval "print('Hello, world');"
Example 2: -eval "return getVersion();"
.fi
.TP
\fB\-run\fR \fICOMMAND\fR
.nf
Runs an ImageJ menu command
Example: -run "About ImageJ..."
.fi
.SH FILES
.TP
.B /usr/share/imageja/plugins/
Plugins for ImageJA should are installed into this directory.
Currently only a single plugins directory is supported, so
if you want to use your own directory, use 

.fi
.SH AUTHOR
Wayne Rasband <wsr@nih.gov> and others.
.SH VERSION
Version 0.9.0
.SH LICENSE
.PP
ImageJA is in the public domain.
